AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Test Pipeline Lambda
Resources:
  CodepipelineFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /Codepipeline
            Method: GET
      Description: ''

